### PR TITLE
added load texture from memory

### PR DESCRIPTION
**Pull request by Frain-Breeze**

### CODE REVIEW

**Comment by Frain-Breeze** [comment]
attempted partial implementation of #12

**Comment by IridescentRose** [comment]
Any progress?

**Comment by IridescentRose** [comment]
@Frain-Breeze Any progress?

**Comment by Frain-Breeze** [comment]
I took a break from PSP programming for a bit, will look into actually getting it working properly soon.

**Comment by IridescentRose** [comment]
Closing for now

**Pull request closed without merging**
